In [0]:
import numpy as np

# Matrices

Create a 2x2 matrix

In [2]:
mat_1 = np.array([[1, 2], [3, 4]])
print(mat_1)

[[1 2]
 [3 4]]


Get the dimension of mat_1

In [3]:
print(mat_1.shape)

(2, 2)


Get the transpose of mat_1

In [4]:
print(mat_1.T)

[[1 3]
 [2 4]]


Unlike python list, we need a more specific value type for the data

In [5]:
print(mat_1.dtype)
mat_another_type = mat_1.astype(np.uint8)
print(mat_another_type.dtype)

int64
uint8


Create a 3x3 identity matrix

In [6]:
mat_2 = np.eye(3, 3)
print(mat_2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a non-square identity matrix (3x5)

In [7]:
mat_3 = np.eye(3, 5)
print(mat_3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


Create a 4x3 matrix with all zero entries

In [8]:
mat_4 = np.zeros((4, 3))
print(mat_4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Create a 2x5 matrix with all one entries

In [9]:
mat_5 = np.ones((2, 5))
print(mat_5)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Create a 3x1 random matrix (every entry is between 0 and 1)

In [10]:
mat_6 = np.random.random((3, 1))
print(mat_6)

[[0.17209914]
 [0.74035539]
 [0.45162013]]


# Matrix concatenation

In [11]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.concatenate((a, b), axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [12]:
print(np.concatenate((a, b.T), axis=1))

[[1 2 5]
 [3 4 6]]


# Matrix slicing

Do matrix slicing on mat_1, to get the lower left element from mat_1

In [13]:
print(mat_1)

[[1 2]
 [3 4]]


In [14]:
print(mat_1[1, 0])

3


Do matrix slicing on mat_1, to get the second row from mat_1

In [15]:
print(mat_1[1, :])

[3 4]


# Loop over matrices

Loop over matrices is slow, should consider using matrix operations, e.g. sum between matrices, dot product

Loop over rows

In [16]:
for row in mat_1:
    print(row)

[1 2]
[3 4]


Loop over every entry:

In [17]:
for row in mat_1:
    for entry in row:
        print(entry)

1
2
3
4


Add one to every entry:

In [18]:
r, c = mat_1.shape
for row in range(r):
    for col in range(c):
        mat_1[row, col] += 1
print(mat_1)

[[2 3]
 [4 5]]


In the last example, an alternative way (and is a better way) is:

In [19]:
mat_1 = mat_1 + 1
print(mat_1)

[[3 4]
 [5 6]]


or equivalently:

In [20]:
mat_1 += 1
print(mat_1)

[[4 5]
 [6 7]]


Adding a number with a matrix will do addition on every entry of the matrix,
 and the same for subtraction, multiplication, division, etc.

# Matrix operations

Operation between two matrices is also point-wise operation.

Note: the two matrices must have same shape

In [21]:
print(mat_1 * mat_1)

[[16 25]
 [36 49]]


Thus the "multiplication" between matrices is not what we define mathematically. To do the linear algebra style multiplication, we need to use function np.matmul

In [22]:
print(np.matmul(mat_1, mat_1))

[[46 55]
 [66 79]]


And we can use np.dot for dot product

In [23]:
print(np.dot(mat_1, mat_1))

[[46 55]
 [66 79]]


Furthermore, we can do cross product

In [24]:
print(np.cross(np.array([1, 2, 3]), np.array([4, 5, 6])))

[-3  6 -3]


# Filtering

Get a boolean matrix showing if the entries can satisfy some condition

In [25]:
print(mat_1 > 5)

[[False False]
 [ True  True]]


Filter out values that doesn't satisfy the condition

In [26]:
mat_1[mat_1 > 5] 

array([6, 7])