# Vector

In [2]:
y <- 5
y -> x
print(x)

[1] 5


In [8]:
print(seq(10, 30, 10))

[1] 10 20 30


In [21]:
# c()-> create a new vector obj
print(x <- c(3, 6, 12, 4))

# use operators on a vector will be processed one by one
print(2*x)

# can be further assigned
print(y <- c(x, x))

# the vector operations can be performed each element, 
# the shorter one will be recycled 
# one vector must be integer times of each other
z <- c(1, 5)
print(sum <- 2*x + y - z)

[1]  3  6 12  4
[1]  6 12 24  8
[1]  3  6 12  4  3  6 12  4
[1]  8 13 35  7  8 13 35  7


# Math opetators

In [49]:
x <- c(3, 6, 12, 4)

# avaiable operations
# + \ - \ * \ / \^:power
# log exp sin cos tan sqrt
print(exp(x)) #20.08554    403.42879 162754.79142     54.59815

# min(vector) max(vector)
print(min(x)) #3

# range: c(min(x), max(x))
print(range(x))#3 12

# length
print(length(x)) #4

# sum, product
print(c(sum(x), prod(x))) #25 864

# mean, variance
print(c(mean(x), var(x))) #6.25 16.25

# sort
print(sort(x)) #3  4  6 12

# parallel max, min
# return the max/min in each position
# the length equals the longest (cause warning)
a <- c(0, 4, 5, 23)
b <- c(5,111,23,23)
print(pmax(a, b)) #5 111  23  23

# complex number need to add the imagery part
print(sqrt(-17+0i)) #0+4.123106i

[1]     20.08554    403.42879 162754.79142     54.59815
[1] 3
[1]  3 12
[1] 4
[1]  25 864
[1]  6.25 16.25
[1]  3  4  6 12
[1]   5 111  23  23
[1] 0+4.123106i


# Sequences

In [69]:
# generate sequence
print(1:4)
print(1:4 -1)
print(1:(4-1))

# seq(from, to, *by, *length)
# from, to: begin, end
# by: the difference between each two number
print(seq(1,2,0.2))
# length: the length of the generated sequence
print(seq(1, 10, length=3))
# seq(along): create a indexing sequence of the given vector 
x <- c(1,3,4,5)
print(seq(along=x))

# rep(obj, times): replicate an obj times end-to-end
print(rep(x, 2))

[1] 1 2 3 4
[1] 0 1 2 3
[1] 1 2 3
[1] 1.0 1.2 1.4 1.6 1.8 2.0
[1]  1.0  5.5 10.0
[1] 1 2 3 4
[1] 1 3 4 5 1 3 4 5


 # Logical operations
&: and, |: or, !: not <br>
Missing values: NA: null obj, NaN: not a number <br>
is.na(x): checks if x is NA <br>
example: NaN: 0/0, Inf-Inf <br>

# Charater Vectors

In [74]:
# paste(obj,...,obj, *sep=" ")
print(paste("x",1:3))
print(paste(c("x","y"), 1:3))
print(paste("x",1:3, sep=":"))

[1] "x 1" "x 2" "x 3"
[1] "x 1" "y 2" "x 3"
[1] "x:1" "x:2" "x:3"


# Indexing Vectors

In [93]:
# x[condition]: recreate a vector that 
# contains all elements TRUE to conditions in the same order
print(x <- c(NA, 2, 2, 2))
print(y <- x[!is.na(x)])

# x[num] returns the num's element of x
# x[begin: end] returns elements in this range, inclusive
# x[-(begin : end)] returns all elemtns thats not in the range

# name(vector) <- vector give the elements names attribute to identify
# x[names] returns all elements in the listed name
x <- 1:5
names(x) <- c("a", "b", "c", "d", "e")
print(x[c("a","b")])

[1] NA  2  2  2
[1] 2 2 2
a b 
1 2 


# Class (Mode)
vectors must have their values all of the same mode. <br>

In [2]:
#as.mode(vector): convert the objs in vector to the mode
z <- 0:3
print(as.character(z))

# mode(): create a new empty vector with the given mode
# the vector can be modified by putting elements into given slot
e <- numeric()
e[3] <- 17
print(e)

[1] "0" "1" "2" "3"
[1] NA NA 17


# Factor
a vector used to specify a discrete classification o the components of other vectors of the same length. 

In [18]:
# factor(vector): make a new, unduplicated factor obj with level attribute
# levels(factor): returns the levels of the factor
x <- factor(c("b", "a", "a", "b", "sd", "sd", "sd"))
print(x)
print(levels(x))

# tapply(vector, factor, operation)
y <- c(3, 2, 9, 12, 5, 5,14)
print(tapply(y, x, mean))

    # writing a function as an operation
    standard_error <- function(x) sqrt(var(x)/length(x))

print(tapply(y, x, standard_error))

[1] b  a  a  b  sd sd sd
Levels: a b sd
[1] "a"  "b"  "sd"
  a   b  sd 
5.5 7.5 8.0 
  a   b  sd 
3.5 4.5 3.0 


# Arrays
a multiply subscripted collection of data entries <br>

In [31]:
x <- 1:8
# dim(vector): create a dimension vector
dim(x) <- c(2,2,2)
print(x)
# find elements by []
print(x[1,1,1])
# leave it empty for the entire dimension
print(x[1,,1])

# the array is indexed as each dimension is filled
print(array(1:20, dim=c(4,5)))

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8

[1] 1
[1] 1 3
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    5    9   13   17
[2,]    2    6   10   14   18
[3,]    3    7   11   15   19
[4,]    4    8   12   16   20


In [37]:
# to assign values for an array
x <- array(1:20, dim=c(4,5))
i <- array(c(1:3,3:1), dim=c(3,2))
x[i] <- NA
print(x)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    5   NA   13   17
[2,]    2   NA   10   14   18
[3,]   NA    7   11   15   19
[4,]    4    8   12   16   20


In [45]:
# array(data_vector, dim_vector): create an array of given data and given dim
# if the given data is shorter than the slots, data will be recycled from the beginning
print(z <- array(c(1,2,3), c(2,3)))

# array can take all operations if all arrays are similar
print(2*z)
x <- array(c(3,2), c(2,3))
print(x+z)

     [,1] [,2] [,3]
[1,]    1    3    2
[2,]    2    1    3
     [,1] [,2] [,3]
[1,]    2    6    4
[2,]    4    2    6
     [,1] [,2] [,3]
[1,]    4    6    5
[2,]    4    3    5


## The recycle rule
expression is scanned from left to right <br>
any short vector operands are extended by recycling values until match the size of others <br>
The arrays must all have the same dim <br>

## Outer product
a,b being two arrays, their outer product is an array whose dimension is got by concatenating their two dimension vectors, and those data vector is got by forming all possible products of elements of the data vector of a with those of b

In [48]:
#outer(array_a, array_b, operation)
x <- array(1:6, c(2,3))
y <- array(2:7, c(3,2))
print(outer(x,y,"*"))

, , 1, 1

     [,1] [,2] [,3]
[1,]    2    6   10
[2,]    4    8   12

, , 2, 1

     [,1] [,2] [,3]
[1,]    3    9   15
[2,]    6   12   18

, , 3, 1

     [,1] [,2] [,3]
[1,]    4   12   20
[2,]    8   16   24

, , 1, 2

     [,1] [,2] [,3]
[1,]    5   15   25
[2,]   10   20   30

, , 2, 2

     [,1] [,2] [,3]
[1,]    6   18   30
[2,]   12   24   36

, , 3, 2

     [,1] [,2] [,3]
[1,]    7   21   35
[2,]   14   28   42



## Matrices and special operations

In [1]:
print(A <-array(1:6, c(2,3)))
print(B <- array(0:5, c(3,2)))

# %*%: matrix multiplication
print(A %*% B)

# crossprod(matrix): crossproduct

# diag(vector): gives a diagonal matrix with the vector being the diagonal
print(diag(1:3))
#diag(matrix): gives the vector of main diagonal entries
print(diag(A))

# eigen(symmetric_matrix)
# return the eignvalues and eigenvectors as a list &val &vec

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
     [,1] [,2]
[1,]    0    3
[2,]    1    4
[3,]    2    5
     [,1] [,2]
[1,]   13   40
[2,]   16   52
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    2    0
[3,]    0    0    3
[1] 1 4


# Lists
an ordered collection of an objs in each components

In [8]:
# list(name_1 = obj_1, ...): create a new list 
lst <- list(name = "Fred", wife = "Mary", no.children = 3, child.age = c(4,7,9))

# The index of a list is as each component
# call the component by $component, or  [["component"]]
print(c(lst$name, lst[["name"]], lst[1]))

[[1]]
[1] "Fred"

[[2]]
[1] "Fred"

$name
[1] "Fred"

[1] 3


## Data frames
a list with class "data.frame" and following the rules <br>
\- The components must be vectors, factors, num matrices, lists, or other data frames <br>
\- Matrices, lists, and data frames provide as many variables to the new data frame as they have columns, elements, or variables <br>
\- Numeric vectors and factors are included as is, and non-numeric vectors are coerced to be factors, whose levels are the unique values appearing in the vector <br>
\- Vector structures appearing as variables of the date frame must all have the same length, and matrix structures must have the same row size.

# Loops
if (logical statement) expr_a else expr_b <br>
for (name in expr_1) expr_2 <br>
repeat expr_1: run the loop until a break, otherwise it will not stop <br>
next: discontinue this loop and skip to the start of the next one <br>
while (logical statement) expr <br>

# Functions 
function_name <- function(parameter,...) { function_body }<br>
called by function_name(parameter)

"%operation_name%" <- function(x,y) {...} <br>
called by x %operation_name% y

<div style= "color: red;"> NOTE: any assignment by &lt;- will only be temporary as in the function, to assign things back to the actual variable, do &lt;&lt;- </div>